/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clase23;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Urpina
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
        
        buttonGroup1.add(rbFemenino);
        buttonGroup1.add(rbMasculino);
        buttonGroup1.add(rbIndefinido);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblTitulo = new javax.swing.JLabel();
        txtValor1 = new javax.swing.JTextField();
        txtValor2 = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();
        txtArea = new javax.swing.JScrollPane();
        txtEmails = new javax.swing.JTextArea();
        txtEmail = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        cmbPais = new javax.swing.JComboBox();
        chkIngles = new javax.swing.JCheckBox();
        chkEspañol = new javax.swing.JCheckBox();
        chkFrances = new javax.swing.JCheckBox();
        btnIdiomas = new javax.swing.JButton();
        rbMasculino = new javax.swing.JRadioButton();
        rbFemenino = new javax.swing.JRadioButton();
        rbIndefinido = new javax.swing.JRadioButton();
        btnValidar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnMenu = new javax.swing.JMenu();
        mnColorRojo = new javax.swing.JMenuItem();
        mnColorAmarillo = new javax.swing.JMenuItem();
        mnColorAzul = new javax.swing.JMenuItem();
        mnColorRosado = new javax.swing.JMenuItem();
        mnColorVerde = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setText("Hola Mundo");
        lblTitulo.setPreferredSize(new java.awt.Dimension(40, 50));

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        txtEmails.setColumns(20);
        txtEmails.setRows(5);
        txtArea.setViewportView(txtEmails);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        cmbPais.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Costa Rica", "Alemania", "Panamá", "España", "Argelia", "Chile", "Japon", "Estados Unidos" }));
        cmbPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPaisActionPerformed(evt);
            }
        });

        chkIngles.setText("Ingles");

        chkEspañol.setText("Español");

        chkFrances.setText("Frances");

        btnIdiomas.setText("Idioma");
        btnIdiomas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIdiomasActionPerformed(evt);
            }
        });

        rbMasculino.setText("Masculino");
        rbMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMasculinoActionPerformed(evt);
            }
        });

        rbFemenino.setText("Femenino");

        rbIndefinido.setText("Indefinido");

        btnValidar.setText("Validar");
        btnValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarActionPerformed(evt);
            }
        });

        mnMenu.setText("Opciones");
        mnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnMenuActionPerformed(evt);
            }
        });

        mnColorRojo.setText("Color Rojo");
        mnColorRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnColorRojoActionPerformed(evt);
            }
        });
        mnMenu.add(mnColorRojo);

        mnColorAmarillo.setText("Color Amarillo");
        mnColorAmarillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnColorAmarilloActionPerformed(evt);
            }
        });
        mnMenu.add(mnColorAmarillo);

        mnColorAzul.setText("Color Azul");
        mnColorAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnColorAzulActionPerformed(evt);
            }
        });
        mnMenu.add(mnColorAzul);

        mnColorRosado.setText("Color Rosado");
        mnColorRosado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnColorRosadoActionPerformed(evt);
            }
        });
        mnMenu.add(mnColorRosado);

        mnColorVerde.setText("Color Verde");
        mnColorVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnColorVerdeActionPerformed(evt);
            }
        });
        mnMenu.add(mnColorVerde);

        jMenuBar1.add(mnMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkIngles)
                    .addComponent(chkEspañol)
                    .addComponent(chkFrances)
                    .addComponent(btnIdiomas))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtEmail)
                    .addComponent(txtArea)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtValor1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(txtValor2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbPais, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnValidar)
                        .addGap(18, 18, 18)
                        .addComponent(rbMasculino)
                        .addGap(51, 51, 51)
                        .addComponent(rbFemenino)
                        .addGap(36, 36, 36)
                        .addComponent(rbIndefinido)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtValor1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnIdiomas))
                    .addComponent(txtValor2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnviar))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregar)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkEspañol)
                        .addGap(18, 18, 18)
                        .addComponent(chkIngles)
                        .addGap(18, 18, 18)
                        .addComponent(chkFrances)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbMasculino)
                    .addComponent(rbFemenino)
                    .addComponent(rbIndefinido)
                    .addComponent(btnValidar))
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        // TODO add your handling code here:
        int resultado = Integer.valueOf(txtValor1.getText()) + Integer.valueOf(txtValor2.getText());
        lblTitulo.setText(String.valueOf(resultado));
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        txtEmails.append(txtEmail.getText() + "\n");
        txtEmail.setText("");
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void cmbPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPaisActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, cmbPais.getSelectedItem());

    }//GEN-LAST:event_cmbPaisActionPerformed

    private void btnIdiomasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIdiomasActionPerformed
        // TODO add your handling code here:
        if (chkEspañol.isSelected()) {
            JOptionPane.showMessageDialog(null, "  Ha seleccionado Español ");
        }
        if (chkIngles.isSelected()) {
            JOptionPane.showMessageDialog(null, "  Ha seleccionado Ingles ");
        }
        if (chkFrances.isSelected()) {
            JOptionPane.showMessageDialog(null, "  Ha seleccionado Frances ");
        }
    }//GEN-LAST:event_btnIdiomasActionPerformed

    private void btnValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarActionPerformed
        // TODO add your handling code here:
        if (rbFemenino.isSelected()) {
            JOptionPane.showMessageDialog(null, "  Ha seleccionado el sexo Femenino ");
        }
        if (rbMasculino.isSelected()) {
            JOptionPane.showMessageDialog(null, "  Ha seleccionado el sexo Masculino ");
        }
        if (rbIndefinido.isSelected()) {
            JOptionPane.showMessageDialog(null, "  Ha seleccionado el sexo Indefinido ");
        }
    }//GEN-LAST:event_btnValidarActionPerformed

    private void mnColorRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnColorRojoActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == mnColorRojo){
            getContentPane().setBackground(Color.red);
        }
    }//GEN-LAST:event_mnColorRojoActionPerformed

    private void mnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnMenuActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == mnColorRojo){
            getContentPane().setBackground(Color.red);
        }
        if(evt.getSource() == mnColorAmarillo){
            getContentPane().setBackground(Color.yellow);
        }
        if(evt.getSource() == mnColorAzul){
            getContentPane().setBackground(Color.blue);
        }
        if(evt.getSource() == mnColorRosado){
            getContentPane().setBackground(Color.pink);
        }
        if(evt.getSource() == mnColorVerde){
            getContentPane().setBackground(Color.green);
        }
    }//GEN-LAST:event_mnMenuActionPerformed

    private void mnColorAmarilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnColorAmarilloActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == mnColorAmarillo){
            getContentPane().setBackground(Color.yellow);
        }
    }//GEN-LAST:event_mnColorAmarilloActionPerformed

    private void rbMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbMasculinoActionPerformed

    private void mnColorAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnColorAzulActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == mnColorAzul){
            getContentPane().setBackground(Color.blue);
        }
    }//GEN-LAST:event_mnColorAzulActionPerformed

    private void mnColorRosadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnColorRosadoActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == mnColorRosado){
            getContentPane().setBackground(Color.pink);
        }
    }//GEN-LAST:event_mnColorRosadoActionPerformed

    private void mnColorVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnColorVerdeActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == mnColorVerde){
            getContentPane().setBackground(Color.green);
        }
    }//GEN-LAST:event_mnColorVerdeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnIdiomas;
    private javax.swing.JButton btnValidar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkEspañol;
    private javax.swing.JCheckBox chkFrances;
    private javax.swing.JCheckBox chkIngles;
    private javax.swing.JComboBox cmbPais;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JMenuItem mnColorAmarillo;
    private javax.swing.JMenuItem mnColorAzul;
    private javax.swing.JMenuItem mnColorRojo;
    private javax.swing.JMenuItem mnColorRosado;
    private javax.swing.JMenuItem mnColorVerde;
    private javax.swing.JMenu mnMenu;
    private javax.swing.JRadioButton rbFemenino;
    private javax.swing.JRadioButton rbIndefinido;
    private javax.swing.JRadioButton rbMasculino;
    private javax.swing.JScrollPane txtArea;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextArea txtEmails;
    private javax.swing.JTextField txtValor1;
    private javax.swing.JTextField txtValor2;
    // End of variables declaration//GEN-END:variables
}
